# Generated by Django 5.0.4 on 2026-03-17 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('icone', models.CharField(default='bi-briefcase', help_text='Classe Bootstrap Icon (ex: bi-graph-up, bi-currency-bitcoin)', max_length=50)),
                ('couleur', models.CharField(default='primary', help_text='Couleur Bootstrap: primary, success, warning, danger, info', max_length=20)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Investissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=15)),
                ('quantite', models.FloatField()),
                ('date_acquisition', models.DateField()),
                ('prix_marche', models.DecimalField(blank=True, decimal_places=2, help_text='Prix actuel sur le marché (pour calculer +/-)', max_digits=15, null=True)),
                ('dividende', models.DecimalField(decimal_places=2, default=0, help_text='Dividende annuel par unité (actions uniquement)', max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investissements', to='portfolio.categorie')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investissements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investissement',
                'verbose_name_plural': 'Investissements',
                'ordering': ['-date_acquisition'],
            },
        ),
    ]
